apiVersion: v1
kind: Namespace
metadata:
  name: jupyter
  labels:
    name: jupyter
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: jupyter
  name: jupyter
  namespace: jupyter
spec:
  replicas: 1
  selector: 
    matchLabels:
      run: jupyter
  template:
    metadata:
      labels:
        run: jupyter
    spec:
      containers:
      - image: jupyter/minimal-notebook:latest
        name: jupyter
      dnsPolicy: ClusterFirst
      restartPolicy: Always

